name: mofc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.5.1
  - pandas=2.2.3
  - torchvision=0.20.1
  - scikit-learn
  - matplotlib
  - tqdm=4.67.1
  - typing_extensions=4.12.2
  - zipp=3.21.0
  - accelerate==1.1.1
  - onnxruntime==1.20.1
  - gdown
  - pip:
    - git 
    - diffusers=0.24.0
    - easydict=1.13
    - transformers=4.46.3
    - triton==2.3.0
    - opencv-python==4.10.0.84
    - invisible_watermark==0.2.0
    - huggingface-hub==0.24.0
    - pyrallis==0.3.1

